data:
  input_csv: "classification_dataset.csv"
  target: "target"
  test_size: 0.2
  random_state: 23

model:
  type: "RandomForest"
  hyperparameters:
    n_estimators: [50, 100, 150]
    max_depth: [5, 10, 15]

training:
  scaling: true

output:
  model_path: "artifacts/model.pkl"
  scaler_path: "artifacts/scaler.pkl"
  metrics_path: "artifacts/metrics.json"
