apiVersion: apps/v1
kind: Deployment
metadata:
  name: titanic-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: titanic-api
  template:
    metadata:
      labels:
        app: titanic-api
    spec:
      containers:
      - name: api
        image: 313110632968.dkr.ecr.us-east-1.amazonaws.com/titanic-fast-new-repo
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
